services:
  auth-db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: auth
    volumes:
      - auth_db_data:/var/lib/postgresql
    ports:
      - "5433:5432"
  
  posts-db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: posts
    volumes:
      - posts_db_data:/var/lib/postgresql
    ports:
      - "5434:5432"
  
  rabbit:
    image: rabbitmq:4-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
    ports:
      - "5672:5672"
      - "15672:15672"
  
  redis:
    image: redis:8-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
  
  redis-insight:
    image: redis/redisinsight:latest
    volumes:
      - redis_insight_data:/data
    ports:
      - "5540:5540"
  
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
  
  gateway-service:
    build:
      context: ./Gateway
    environment:
      - ASPNETCORE_HTTP_PORTS=5000
    ports:
      - "5000:5000"
    depends_on:
      - auth-service
      - posts-service

  auth-service:
    build:
      context: ./Auth.API
    environment:
      - ConnectionStrings__DefaultConnection=Host=auth-db;Database=auth;Username=postgres;Password=1234
      - RabbitMQ__Host=rabbit
      - Redis__Host=redis
      - ASPNETCORE_HTTP_PORTS=7001;7002
      - ASPNETCORE_KESTREL__ENDPOINTS__HTTP__URL=http://*:7001
      - ASPNETCORE_KESTREL__ENDPOINTS__HTTP__PROTOCOLS=Http1
      - ASPNETCORE_KESTREL__ENDPOINTS__GRPC__URL=http://*:7002
      - ASPNETCORE_KESTREL__ENDPOINTS__GRPC__PROTOCOLS=Http2
    ports:
      - "7001:7001" # REST
      - "7002:7002" # gRPC
    depends_on:
      - auth-db
      - rabbit
      - redis

  posts-service:
    build:
      context: ./Posts.API
    environment:
      - ConnectionStrings__DefaultConnection=Host=posts-db;Database=posts;Username=postgres;Password=1234
      - AuthService__GrpcUrl=http://auth-service:7002
      - ASPNETCORE_HTTP_PORTS=7003
    ports:
      - "7003:7003"
    depends_on:
      - posts-db
      - auth-service
  
  notification-service:
    build:
      context: ./Notification.API
    environment:
      - RabbitMQ__Host=rabbit
      - ASPNETCORE_HTTP_PORTS=7004
    ports:
      - "7004:7004"
    depends_on:
      - rabbit

volumes:
  auth_db_data:
  posts_db_data:
  rabbitmq_data:
  redis_data:
  redis_insight_data:
  prometheus_data:
  grafana_data: