services:
  auth-db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: auth
    ports:
      - "5433:5432"
  
  notes-db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: notes
    ports:
      - "5434:5432"
  
  rabbit:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
  
  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
  
  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"